name: Windows build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Release x64
        run: msbuild Qt6PaltalkTimerX64.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Qt6PaltalkTimerX64-Release-x64
          path: |
            x64/Release/*.exe
            x64/Release/*.dll
